# Generated by Django 6.0.3 on 2026-03-31 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0003_category_search_data_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='Uncategorize'),
        ),
    ]
