# Generated by Django 6.0.3 on 2026-03-31 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0004_alter_category_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_data',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
