# Generated by Django 6.0.3 on 2026-03-31 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0006_category_search_data_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search_data',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
