# Generated by Django 6.0.3 on 2026-04-09 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0009_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user'),
        ),
    ]
