# Generated by Django 6.0.3 on 2026-05-24 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0017_order_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resume/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
