# Generated by Django 6.0.3 on 2026-05-26 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0018_resume'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
